#!/usr/bin/env zsh

# Processes a USAA-formatted CSV transaction list for consumption by YNAB

if ! (( $+commands[sponge] )); then
	if read -q "choice?Sponge required, would you like to install now? [y/N] "; then
		sudo apt update && sudo apt install moreutils
	else
		echo "Exiting..."
		exit 0
	fi
fi

file="/home/jmt/Downloads/bk_download.csv"

<<< 'a,b,Date,c,Payee,d,Amount' < "$file" | sponge "$file"

echo "Done"
